### ISSUE TITLE
How does EdgeFormer perform on scene text recognition (STR)?

### ISSUE THREAD

**Issue by SamChen** [hkzhang91/EdgeFormer#10]
Hi,

Thanks for sharing the code. EdgeFormer is a very interesting architecture. 

Do you test the architecture on STR? If so, can you share the testing results?

Thanks :-)

**Comment by hkzhang-git** [comment]
I did not apply and test Edgeformer on STR. Three vision tasks I tested on are image classification, semantice segmentation and object detection.
