### ISSUE TITLE
Global Circular Conv Difference

### ISSUE THREAD

**Issue by nviwch** [hkzhang91/EdgeFormer#12]
In your code, there is gcc_ca and gcc_dk, I am interesed in the dynamic kernel, how does it perform? Your default config used gcc_ca only.

The original version is constant kernel size and bilinear interpolate to H or W shape.

Dynamic version is dynamic kernel size using taking average of the input in different axis and conv the result as the kernel which is an interesting idea, and it does seem better?

**Comment by hkzhang-git** [comment]
The depth wise dynamic kernel in the submitted code does not achieve better performance. We still working on this part. According to experimental results we have now, using group verision dynamic kernel may achieve competitive performance. I hope this answer is useful for you.
