### ISSUE TITLE
A small question about you paper?

### ISSUE THREAD

**Issue by yongjiezhu1998** [hkzhang91/EdgeFormer#13]
Hello,congratulation your paper has been accepted by ECCV. But I saw your paper's name has been changed.And some module's names also changed. Edgeformer block has changed to PaCC block,GCC-V and GCC-H had changed to PaCC-V and PaCC-H.First in your Figure 1 GCC-H and GCC-V not changed, Second why changed them all to PaCC xxx, ?

**Comment by hkzhang-git** [comment]
Thanks for pointing this out, this is typo, which has been corrected now.  

During peer review stage, one reviewer suggest us to change the name EdgeFormer. Calling the model EdgeFormer is misleading as the model is purely convolution based. A community standard, "Former" as a postfix almost suggests that the model is some variant of transformer. We accept this suggestion and change the name of the proposed method when preparing carema ready version.
