### ISSUE TITLE
ParC block 的代码在哪个.py里面？

### ISSUE THREAD

**Issue by qinhuanghanwuhenniubi** [hkzhang91/EdgeFormer#14]

**Comment by hkzhang-git** [comment]
./cvnets/modules/edgeformer_block.py,  254 行就是。这个网络以前叫做edgeformer，所以你顺着edgeformer , gcc  关键词搜索就行。论文改了名称，代码里还没改过来。

**Comment by qinhuanghanwuhenniubi** [comment]
好的

**Comment by FeiXie8** [comment]
> ./cvnets/modules/edgeformer_block.py, 254 行就是。这个网络以前叫做edgeformer，所以你顺着edgeformer , gcc 关键词搜索就行。论文改了名称，代码里还没改过来。

您好实在不好意思打扰了，请问一下这里面的gcc_mf_block和gcc_dk，哪一个是论文当中的即插即用的parc-block呢
