### ISSUE TITLE
when running model_convert2onnx.py, having a problem, where i find a example?

### ISSUE THREAD

**Issue by winterxx** [hkzhang91/EdgeFormer#15]
RuntimeError: Unsupported: ONNX export of convolution for kernel of unknown shape.

**Comment by hkzhang-git** [comment]
This problem has been discussed and solved, please find in #3 . I hope this is useful for you.

**Comment by winterxx** [comment]
Thanks! it's work from .pth to .onnx, but from .onnx to .rknn is BatchNormal error, my plateform is rv1126.

**Comment by hkzhang-git** [comment]
I do not have much experimence on testing on RK 3288. My colleague helped me to finished this step. Can you provided more details about you error. Maybe I can get some adivces from colleague to help you in your case.

**Comment by winterxx** [comment]
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1710, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1602, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 292, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 129, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1718, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match layer: BatchNormalization_BatchNormalization_975:out0 failed!

**Comment by hkzhang-git** [comment]
I have asked my colleague, he deployed the proposed model on RK3288 by converting onnx model with mnn, which is different from rknn you adopted. Therefore, we can not provide some useful information for you.

**Comment by winterxx** [comment]
ok,thanks
