### ISSUE TITLE
Image segmentation dataset problem

### ISSUE THREAD

**Issue by zhang-pan** [hkzhang91/EdgeFormer#18]
I see the following examples of data sets given in your code:
Dataset class for the PASCAL VOC 2012 dataset

        The structure of PASCAL VOC dataset should be something like this
        + pascal_voc/VOCdevkit/VOC2012/
        + --- Annotations
        + --- JPEGImages
        + --- SegmentationClass
        + --- SegmentationClassAug_Visualization/
        + --- ImageSets
        + --- list
        + --- SegmentationClassAug
        + --- SegmentationObject

However, there are only a few files in the dataset I downloaded：
![image](https://user-images.githubusercontent.com/26357074/187200230-81fa4454-f086-402a-a92b-360df6f0d707.png)

I want to know how these files are generated?
+ --- SegmentationClassAug_Visualization/
+ --- list
+ --- SegmentationClassAug

**Comment by hkzhang-git** [comment]
I have uploaded all these files to my web disk. You can download these files from the following link: https://pan.baidu.com/s/1G_aNkHvbsQq_i_m82mYMLg 
Fetch code: segp
