### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by yingqiluoCSDN** [hkzhang91/EdgeFormer#19]
您好，我想请问一下数据集的格式是怎样的？我按照您代码上下载数据集但并不完整

**Comment by zhang-pan** [comment]
我也遇到了数据集的问题，分割数据集下载下来缺少相关代码中提及的文件，你呢？

**Comment by hkzhang-git** [comment]
我把处理好的数据共享到百度网盘了，你可以直接下载
https://pan.baidu.com/s/1G_aNkHvbsQq_i_m82mYMLg
提取码: segp
