### ISSUE TITLE
How to convert .pt to .onnx for segmentation model?

### ISSUE THREAD

**Issue by lws6885** [hkzhang91/EdgeFormer#21]

**Comment by hkzhang-git** [comment]
We did not convert the segmentation model to .onnx. But the code part should be same with that in coverting classification model , which has been explained in response issue #3

**Comment by lws6885** [comment]
Thanks!
















At 2022-09-13 10:00:59, "hkzhang91" ***@***.***> wrote:

We did not convert the segmentation model to .onnx. But the code part should be same with that in coverting classification model , which has been explained in response issues #3
