### ISSUE TITLE
cannot import name 'check_frozen_norm_layer' from 'utils.common_utils'

### ISSUE THREAD

**Issue by napohou** [hkzhang91/EdgeFormer#22]
Hi author,
When I run the command:
CUDA_VISIBLE_DEVICES=0 python eval_det.py --common.config-file ./config/detection/edgeformer/ssd_edgeformer_s.yaml --model.detection.pretrained ./pretrained_models/detection/checkpoint_ema_avg.pt --evaluation.detection.mode validation_set --evaluation.detection.resize-input-images
I get this error. Can you tell me what to do now?

**Comment by napohou** [comment]
fixed.

**Comment by Li-Ziheng** [comment]
> fixed.
How did you solve the problem?
