### ISSUE TITLE
where does parc defined, is same as edgeformer？

### ISSUE THREAD

**Issue by lucasjinreal** [hkzhang91/EdgeFormer#26]
where does parc defined, is same as edgeformer？

**Comment by Qm-jmz** [comment]
我想你的问题可以在[13#](https://github.com/hkzhang91/ParC-Net/issues/13)和[14#](https://github.com/hkzhang91/ParC-Net/issues/14#)得到解答？

**Comment by lucasjinreal** [comment]
thanks, the code edgeformer is very confusing... it would be better sync with your paper,.

**Comment by hkzhang-git** [comment]
Sorry to rely so late. We change the name from edgeformer to  ParC-Net following reviewer's suggetion but do not update the code yet. I really appreciate your suggestion.  I will update it after submission ddl of CVPR 2023
