### ISSUE TITLE
模块替换

### ISSUE THREAD

**Issue by yingqiluoCSDN** [hkzhang91/EdgeFormer#28]
edgeformer_block.py中的 gcc_dk就是readme里边替换了convnext 的dwconv 7*7 结构吗？

**Comment by hkzhang-git** [comment]
我后边会更新一下这个代码，把parc 版本的其他模型也开源了，等我忙完11月11号之后哈，抱歉

**Comment by yingqiluoCSDN** [comment]
我将edgeformer_block.py中的 gcc_dk替换掉传统卷积操作，这样可以吗？
