### ISSUE TITLE
算法运行问题

### ISSUE THREAD

**Issue by yingqiluoCSDN** [hkzhang91/EdgeFormer#29]
在运行算法时，会报“TypeError: unsupported operand type(s) for %: 'Sequential' and 'Sequential'”问题，是否由于class gcc_dk(nn.Module)中的self.kernel_generate_conv = nn.Sequential(
                nn.Conv2d(channel, channel, kernel_size=(3, 1), padding=(1, 0), bias=False, groups=channel),
                nn.BatchNorm2d(channel),
                nn.Hardswish(),
                nn.Conv2d(channel, channel, kernel_size=(3, 1), padding=(1, 0), bias=False, groups=channel),
            )出现了问题？

**Comment by hkzhang-git** [comment]
dynamic kernel (dk) 版本是我后续的一点实验工作，目前这个效果还不好。推荐使用基础的版本哈
