### ISSUE TITLE
Convert to ONNX problem

### ISSUE THREAD

**Issue by bankholdup** [hkzhang91/EdgeFormer#3]
Hi!

I'm trying to convert EdgeFormer model from .pt to .onnx via your example model_convert2onnx.py, and I get following error:

RuntimeError: Unsupported: ONNX export of convolution for kernel of unknown shape.

**Comment by hkzhang-git** [comment]
The version that contains instantly generated kernel is not supported to convert to .onnx. In order to convert the pretrained model, embeding pretrined kernels into conv layers which have fixed kernel sizes is necessary. 

You can init such a model referring to the following code:

![image](https://user-images.githubusercontent.com/41274618/165937917-af42a368-68c0-431b-be9d-5c360d585bec.png)

**Comment by bankholdup** [comment]
Thanks for your answer! I'll try it and let you know

**Comment by KelOdgSmile** [comment]
For anyone who would like a more complete implementation I'm attaching links to a fork which successfully  moved the learned weights to a new static kernel.(Outputs verified to be same between networks for same input). This is a barebones implementation which is not guaranteed to work with all model configurations but works for the one presently hardcoded. I would not just copy the code as its provided to make the transition easier for you. The underlying EdgeFormer repo has been refactored in many ways based on my own use-case.


Implementation of static kernel for gcc_ca_mf:

https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/EdgeFormer/cvnets/modules/edgeformer_block.py#L812


Code to move weights from a trained gcc_ca_mf network with dynamic kernel to gcc_ca_mf with static kernel:

https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/model_convert2onnx.py#L64

These two lines are how I switch between calling a model with dynamic and static kernel:

https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/EdgeFormer/cvnets/modules/edgeformer_block.py#L936

https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/model_convert2onnx.py#L57

**Comment by bankholdup** [comment]
> For anyone who would like a more complete implementation I'm attaching links to a fork which successfully moved the learned weights to a new static kernel.(Outputs verified to be same between networks for same input). This is a barebones implementation which is not guaranteed to work with all model configurations but works for the one presently hardcoded. I would not just copy the code as its provided to make the transition easier for you. The underlying EdgeFormer repo has been refactored in many ways based on my own use-case.
> 
> Implementation of static kernel for gcc_ca_mf:
> 
> https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/EdgeFormer/cvnets/modules/edgeformer_block.py#L812
> 
> Code to move weights from a trained gcc_ca_mf network with dynamic kernel to gcc_ca_mf with static kernel:
> 
> https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/model_convert2onnx.py#L64
> 
> These two lines are how I switch between calling a model with dynamic and static kernel:
> 
> https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/EdgeFormer/cvnets/modules/edgeformer_block.py#L936
> 
> https://github.com/KelOdgSmile/EdgeFormer/blob/3256c483967293f9f3b88b72c8b16b68b03a8461/model_convert2onnx.py#L57

Thanks! It's really working.
