### ISSUE TITLE
How to use gcc with pretrained model?

### ISSUE THREAD

**Issue by kings-rgb** [hkzhang91/EdgeFormer#6]
In paper and code, the _meta_kernel_size_ is fixed in training. The _meta_kernel_size_ is calculated by input size(256 in code), so the inference size should be less than 256. If I want to use the pretrained model in other work with different input size, the _meta_kernel_size_ is incompatible.

**Comment by hkzhang-git** [comment]
In fact, you do not have to care about the meta_kernel_size. During inference or training, kernels acturally involved in computation are instance kernels, which are derived from meta kernel while sizes of which are depends on the size of input features.  For instance, in our experiments, we just train one model on imagenet with input size of 256 and finetune the trained model on segmentation dataset with input size of 512 and detection dataset with input size of 320.
