### ISSUE TITLE
即插即用

### ISSUE THREAD

**Issue by xiaoyudanaa** [hkzhang91/EdgeFormer#7]
您好，看到您的代码后很受启发，想引用您这个项目。但我没看懂哪个模块是即插即用的，还有该如何把这个模块放到我自己的模型中。期待您的回复

**Comment by hkzhang-git** [comment]
两种方式：
1）在深层结构部分，用GCC 替换网络里原有的 conv 层，就像readme里边 替换了convnext 的dwconv 7*7 结构。
2）用edgeformer block 替换深层部分block. 
整体结构依然保持浅层是纯conv 提取local feature， 深层考虑用复杂一点结构提取global feature, 或local-global feature.

**Comment by FeiXie8** [comment]
> 您好，请问一下 2）用edgeformer block 替换深层部分block. 中的edgeformer block是edgeformer_block中的哪一个结构呢
