### ISSUE TITLE
ModuleNotFoundError: No module named 'data.sampler'

### ISSUE THREAD

**Issue by DDxk369** [hkzhang91/EdgeFormer#8]
您好，感谢您提供了这一富有创造性的想法，但是当我试图运行`main_train.py`时，发现options路径下并没有data文件，这一缺失导致代码第一步就无法正常运行，请您查看下，谢谢

Traceback (most recent call last):
  File "main_train.py", line 6, in <module>
    from options.opts import get_training_arguments
  File "/content/EdgeFormer/options/opts.py", line 3, in <module>
    from data.sampler import arguments_sampler
ModuleNotFoundError: No module named 'data.sampler'

**Comment by KelOdgSmile** [comment]
I ran into this problem as well. It comes from the code having been sort of rigged into apples repo https://github.com/apple/ml-cvnets
You can join the two repos yourself or if you just want to extract the model you can safely remove a lot of the imports and call the model builder in your code.

**Comment by DDxk369** [comment]
thankyou  ：）

**Comment by hkzhang-git** [comment]
thanks you guys for your interesting, please wait me a few days. I'm writing rebuttals recently. I will check this problem and solve it  asap. Thanks for your patience.

**Comment by hkzhang-git** [comment]
Dataloader related files( including smaplers, transforms, etc.) have been uploaded.
